nodeLinker: pnp

packageExtensions:
  babel-loader@*:
    dependencies:
      webpack: "*"
  eslint-config-airbnb-base@*:
    dependencies:
      eslint: "*"
      eslint-plugin-import: "*"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: "@yarnpkg/plugin-typescript"
  - path: .yarn/plugins/@yarnpkg/plugin-version.cjs
    spec: "@yarnpkg/plugin-version"
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"

pnpEnableEsmLoader: true

pnpMode: loose

yarnPath: .yarn/releases/yarn-3.2.0.cjs
