nodeLinker: pnp

packageExtensions:
  "@babel/plugin-transform-react-jsx@*":
    dependencies:
      "@babel/core": "*"
  "@babel/preset-env@*":
    dependencies:
      "@babel/core": "*"
  babel-loader@*:
    dependencies:
      webpack: "*"
  eslint-config-airbnb-base@*:
    dependencies:
      eslint: "*"
      eslint-plugin-import: "*"
  fork-ts-checker-webpack-plugin@*:
    dependencies:
      typescript: "*"
      webpack: "*"
  react-server-dom-webpack@*:
    dependencies:
      webpack: "*"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: "@yarnpkg/plugin-typescript"
  - path: .yarn/plugins/@yarnpkg/plugin-version.cjs
    spec: "@yarnpkg/plugin-version"

yarnPath: .yarn/releases/yarn-3.1.1.cjs
