name: Coverage

on: [pull_request]

jobs:
  if: ${{ false }} # disable for now
  coverage:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: yarn
      - run: yarn install --check-cache
      - run: yarn test:coverage
