name: E2E

on: [push, pull_request]

jobs:
  pre_job:
    runs-on: ubuntu-latest
    outputs:
      should_skip: ${{ steps.skip_check.outputs.should_skip }}
    steps:
      - id: skip_check
        uses: fkirc/skip-duplicate-actions@master
        with:
          concurrent_skipping: 'same_content_newer'

  build:
    if: ${{ needs.pre_job.outputs.should_skip != 'true' }}
    timeout-minutes: 10
    runs-on: ubuntu-latest
    needs: [pre_job]
    permissions:
      contents: 'read'
      id-token: 'write'
    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v3

      - name: Get and modify .env file
        run: |
          cp .env.local.example .env.local
          sed -i 's@\(FORK_RPC_URL\=\).*@\1${{ secrets.ROPSTEN_FORK_RPC_URL }}@' .env.local
          cat .env >> $GITHUB_ENV

      - id: 'auth'
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'

      - id: 'get-credentials'
        uses: 'google-github-actions/get-gke-credentials@v0'
        with:
          cluster_name: 'ens-test-env-gke'
          location: 'asia-southeast1-b'

      - uses: imranismail/setup-kustomize@v1

      - name: 'Create test environment'
        run: |
          date +%s > .time
          kustomize edit set label commit:$(git rev-parse HEAD)
          kustomize edit set label time:$(cat .time)
          kustomize edit set namesuffix -- -$(echo "$(cat .time)-$(git rev-parse HEAD)" | cksum | cut -f 1 -d ' ')
          kubectl create -k ./

      - uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'yarn'

      - run: yarn install --immutable

      - run: yarn e2e

      - name: Cleanup Kubernetes
        if: always()
        run: kubectl delete -k ./ --wait=false --force --grace-period=0 || exit 0

      - uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: synpress-screenshots
          path: e2e/screenshots
      # Test run video was always captured, so this action uses "always()" condition
      - uses: actions/upload-artifact@v2
        if: always()
        with:
          name: synpress-videos
          path: e2e/videos
