name: E2E

on: [push, pull_request]

jobs:
  pre_job:
    runs-on: ubuntu-latest
    outputs:
      should_skip: ${{ steps.skip_check.outputs.should_skip }}
    steps:
      - id: skip_check
        uses: fkirc/skip-duplicate-actions@master
        with:
          concurrent_skipping: 'same_content_newer'

  yarn_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'yarn'

      - run: yarn install --immutable --check-cache

      - name: Upload .yarn
        uses: actions/upload-artifact@v3
        with:
          name: yarn-${{ github.sha }}
          path: .yarn
          retention-days: 1

  stateful:
    if: ${{ needs.pre_job.outputs.should_skip != 'true' }}
    timeout-minutes: 10
    runs-on: ubuntu-latest
    needs: [pre_job, yarn_check]
    strategy:
      matrix:
        node-version: [1, 2]

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Download .yarn
        uses: actions/download-artifact@v3
        with:
          name: yarn-${{ github.sha }}

      - run: yarn buildandstart & yarn wait-on http://localhost:3000 && yarn synpress:ci:stateful --parallel --ci-build-id ${{ github.sha }}-${{ github.workflow }}-${{ github.event_name }}

      - uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: synpress-screenshots
          path: e2e/screenshots

      - uses: actions/upload-artifact@v2
        if: always()
        with:
          name: synpress-videos
          path: e2e/videos
