name: E2E

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v2
      - name: Modify env file
        working-directory: ./test-environment
        run: |
          copy .env.example .env
          sed -i 's/\(FORK_RPC_URL\=\).*/\1${{ secrets.FORK_RPC_URL }}/' .env
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: yarn
      - run: yarn install
      - run: yarn e2e:ci
