name: E2E

on: [push, pull_request]

jobs:
  pre_job:
    runs-on: ubuntu-latest
    outputs:
      should_skip: ${{ steps.skip_check.outputs.should_skip }}
    steps:
      - id: skip_check
        uses: fkirc/skip-duplicate-actions@master
        with:
          concurrent_skipping: "same_content"

  build:
    if: ${{ needs.pre_job.outputs.should_skip != 'true' }}
    runs-on: ubuntu-latest
    needs: [pre_job]
    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v2

      - name: Modify env file
        working-directory: ./test-environment
        run: |
          cp .env.example .env
          sed -i 's@\(FORK_RPC_URL\=\).*@\1${{ secrets.FORK_RPC_URL }}@' .env
          cat .env >> $GITHUB_ENV

      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: yarn

      - run: yarn install
      - name: Get cached test-environment file
        uses: actions/cache@v2
        with:
          path: ${{ env.GITHUB_WORKSPACE }}/test-environment/archives/data_${{ env.BLOCK_HEIGHT }}_${{ env.SUBGRAPH_ID }}_${{ env.EPOCH_TIME }}.archive.tar.lz4
          key: data-${{ env.BLOCK_HEIGHT }}-${{ env.SUBGRAPH_ID }}-${{ env.EPOCH_TIME }}
          restore-keys: data-${{ env.BLOCK_HEIGHT }}-${{ env.SUBGRAPH_ID }}-${{ env.EPOCH_TIME }}

      - run: yarn e2e:ci
