name: Test

on: [push]

env:
  SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}

jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2.2.2
        with:
          version: 7.8.0

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'pnpm'

      - run: pnpm install --frozen-lockfile

      - run: pnpm test:coverage

  stateless:
    timeout-minutes: 20
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2.2.2
        with:
          version: 7.8.0

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'pnpm'

      - run: pnpm install --frozen-lockfile

      - name: Pull metadata service image
        run: |
          echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u $ --password-stdin
          docker pull ghcr.io/ensdomains/ens-metadata-service:latest

      - name: Run tests
        run: pnpm e2e:ci

      - uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: synpress-screenshots
          path: e2e/screenshots

      - uses: actions/upload-artifact@v2
        if: always()
        with:
          name: synpress-videos
          path: e2e/videos

  stateful:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [1, 2]

    steps:
      - uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2.2.2
        with:
          version: 7.8.0

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'pnpm'

      - run: pnpm install --frozen-lockfile

      - run: pnpm rebuild -r

      - name: Run tests
        run: 'parallel --lb --halt now,success=1,fail=1 ::: \
          "pnpm buildandstart" \
          "pnpm wait-on http://localhost:3000 && pnpm synpress:ci:stateful --parallel --ci-build-id ${{ github.sha }}-${{ github.workflow }}-${{ github.event_name }}"'
        env:
          NEXT_PUBLIC_GRAPH_URI: https://api.thegraph.com/subgraphs/name/tateb/enssubdomaincount

      - uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: synpress-screenshots
          path: e2e/screenshots

      - uses: actions/upload-artifact@v2
        if: always()
        with:
          name: synpress-videos
          path: e2e/videos
